x-minio-common: &minio-common
  image: minio/minio:latest
  command: server --console-address ":9001" http://minio{1...2}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: numbernine
    MINIO_ROOT_PASSWORD: numbernine
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

services:

  #-----------------------------------------------------
  # river queue watcher
  #-----------------------------------------------------
  ui:
    image: ghcr.io/riverqueue/riverui:latest
    ports:
      - 11111:8080
    environment:
      DATABASE_URL: postgresql://postgres@jemison-queues-db:5432/postgres
      RIVER_LOG_LEVEL: ERROR
      RIVER_DEBUG: 0
    depends_on:
      jemison-queues-db:
        condition: service_healthy

  #-----------------------------------------------------
  # postgres common
  #-----------------------------------------------------
  x-pg-common: &pg-common
    image: postgres:16-alpine
    environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready", "-d", "postgres", "-U", "postgres"]
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  

  #-----------------------------------------------------
  # postgres/jemison-queues-db :5432
  #-----------------------------------------------------
  jemison-queues-db:
    <<: *pg-common
    ports:
      - 5432:5432
    volumes:
      - jemison-queues-db-vol:/var/lib/postgresql/data

  #-----------------------------------------------------
  # postgres/jemison-work-db :6543
  #-----------------------------------------------------
  jemison-work-db:
    <<: *pg-common
    ports:
      - 6543:5432
    volumes:
      - jemison-work-db-vol:/var/lib/postgresql/data

  #-----------------------------------------------------
  # search jemison-search-db :7654
  #-----------------------------------------------------
  jemison-search-db:
    <<: *pg-common
    ports:
      - 7654:5432
    volumes:
      - jemison-search-db-vol:/var/lib/postgresql/data



  #-----------------------------------------------------
  # minio :9001
  #-----------------------------------------------------
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost || exit 1"]
      timeout: 10s


  #-----------------------------------------------------
  # pgweb:5432
  #-----------------------------------------------------
  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb 
    restart: always
    ports: 
      - 22222:8081
    environment:
      PGWEB_DATABASE_URL: postgresql://postgres@jemison-queues-db:5432/postgres?sslmode=disable
    depends_on:
      jemison-queues-db:
        condition: service_healthy

  #-----------------------------------------------------
  # pgweb:6543
  #-----------------------------------------------------
  pgweb2:
    image: sosedoff/pgweb
    container_name: pgweb2
    restart: always
    ports: 
      - 22223:8081
    environment:
      PGWEB_DATABASE_URL: postgresql://postgres@jemison-work-db:5432/postgres?sslmode=disable
    depends_on:
      jemison-queues-db:
        condition: service_healthy

volumes:
  jemison-queues-db-vol:
  jemison-work-db-vol:
  jemison-search-db-vol:
  data1-1:
  data1-2:
  data2-1:
  data2-2: