services:

  #-----------------------------------------------------
  # river queue watcher
  #-----------------------------------------------------
  ui:
    image: ghcr.io/riverqueue/riverui:latest
    ports:
      - 11111:8080
    environment:
      DATABASE_URL: postgresql://postgres@jemison-queues-db:5432/postgres
      RIVER_LOG_LEVEL: ERROR
      RIVER_DEBUG: 0
    depends_on:
      jemison-queues-db:
        condition: service_healthy

  #-----------------------------------------------------
  # postgres - jemison-queues-db
  #-----------------------------------------------------
  jemison-queues-db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - jemison-queues-db-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready", "-d", "postgres", "-U", "postgres"]
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  #-----------------------------------------------------
  # postgres - jemison-work-db
  #-----------------------------------------------------
  jemison-work-db:
    image: postgres:16-alpine
    ports:
      - 6543:5432
    volumes:
      - jemison-work-db-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready", "-d", "postgres", "-U", "postgres"]
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  

  #-----------------------------------------------------
  # minio
  #-----------------------------------------------------
  minio:
    image: minio/minio:latest
    hostname: minio
    command: server /data --console-address ":9001" 
    expose:
      - "9000"
      - "9001"
    ports:
      - 9001:9000
      - 9002:9001
    environment:
      MINIO_ROOT_USER: numbernine
      MINIO_ROOT_PASSWORD: numbernine
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5    
    volumes:
      - minio-data:/data

  #-----------------------------------------------------
  # pgweb:5432
  #-----------------------------------------------------
  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb 
    restart: always
    ports: 
      - 22222:8081
    environment:
      PGWEB_DATABASE_URL: postgresql://postgres@jemison-queues-db:5432/postgres?sslmode=disable
    depends_on:
      jemison-queues-db:
        condition: service_healthy

  #-----------------------------------------------------
  # pgweb:6543
  #-----------------------------------------------------
  pgweb2:
    image: sosedoff/pgweb
    container_name: pgweb2
    restart: always
    ports: 
      - 22223:8081
    environment:
      PGWEB_DATABASE_URL: postgresql://postgres@jemison-work-db:5432/postgres?sslmode=disable
    depends_on:
      jemison-queues-db:
        condition: service_healthy

volumes:
  jemison-queues-db-vol:
  jemison-work-db-vol:
  minio-data: