services:

  #-----------------------------------------------------
  # fetch
  #-----------------------------------------------------
  fetch:
    container_name: fetch
    image: eight/dev
    build: 
      context: .
      dockerfile: ./cmd/fetch/Dockerfile
    entrypoint: /home/vcap/app/cmd/fetch/run-fast.sh
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - 10000:8888
    # https://docs.docker.com/compose/how-tos/startup-order/
    depends_on:
      minio:
        condition: service_healthy
      queue-db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://fetch:8888/heartbeat || exit 1
      interval: 60s
      timeout: 180s
      retries: 3
      start_period: 60s
    environment:
      ENV: "DOCKER"
    restart: always

  #-----------------------------------------------------
  # extract
  #-----------------------------------------------------
  extract:
    container_name: extract
    image: eight/dev
    build: 
      context: .
      dockerfile: ./cmd/extract/Dockerfile
    entrypoint: /home/vcap/app/cmd/extract/run-fast.sh
    volumes:
      - type: bind
        source: .
        target: /home/vcap/app
    ports:
      - 10001:8888
    # https://docs.docker.com/compose/how-tos/startup-order/
    depends_on:
      minio:
        condition: service_healthy
      queue-db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://extract:8888/heartbeat || exit 1
      interval: 60s
      timeout: 180s
      retries: 3
      start_period: 60s
    environment:
      ENV: "DOCKER"
    restart: always

  #-----------------------------------------------------
  # walk
  #-----------------------------------------------------
  walk:
    container_name: walk
    image: eight/dev
    build: 
      context: .
      dockerfile: ./cmd/walk/Dockerfile
    entrypoint: /home/vcap/app/cmd/walk/run-fast.sh
    volumes:
      - type: bind
        source: .
        target: /home/vcap/app
    ports:
      - 10002:8888
    # https://docs.docker.com/compose/how-tos/startup-order/
    depends_on:
      minio:
        condition: service_healthy
      queue-db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://walk:8888/heartbeat || exit 1
      interval: 60s
      timeout: 180s
      retries: 3
      start_period: 60s
    environment:
      ENV: "DOCKER"
    restart: always

  #-----------------------------------------------------
  # pack
  #-----------------------------------------------------
  pack:
    container_name: pack
    image: eight/dev
    build: 
      context: .
      dockerfile: ./cmd/pack/Dockerfile
    entrypoint: /home/vcap/app/cmd/pack/run-fast.sh
    volumes:
      - type: bind
        source: .
        target: /home/vcap/app
    ports:
      - 10003:8888
    # https://docs.docker.com/compose/how-tos/startup-order/
    depends_on:
      minio:
        condition: service_healthy
      queue-db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://pack:8888/heartbeat || exit 1
      interval: 60s
      timeout: 180s
      retries: 3
      start_period: 60s
    environment:
      ENV: "DOCKER"
    restart: always

  #-----------------------------------------------------
  # serve
  #-----------------------------------------------------
  serve:
    container_name: serve
    image: eight/dev
    build: 
      context: .
      dockerfile: ./cmd/serve/Dockerfile
    entrypoint: /home/vcap/app/cmd/serve/run-fast.sh
    volumes:
      - type: bind
        source: .
        target: /home/vcap/app
    ports:
      - 10004:8888
    # https://docs.docker.com/compose/how-tos/startup-order/
    depends_on:
      minio:
        condition: service_healthy
      queue-db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://serve:8888/heartbeat || exit 1
      interval: 60s
      timeout: 180s
      retries: 3
      start_period: 60s
    environment:
      ENV: "DOCKER"
    restart: always

  #-----------------------------------------------------
  # river queue watcher
  #-----------------------------------------------------
  ui:
    image: ghcr.io/riverqueue/riverui:latest
    ports:
      - 11111:8080
    environment:
      DATABASE_URL: postgresql://postgres@queue-db:5432/postgres
      RIVER_LOG_LEVEL: ERROR
      RIVER_DEBUG: 0
    depends_on:
      queue-db:
        condition: service_healthy

  #-----------------------------------------------------
  # postgres - queue-db
  #-----------------------------------------------------
  queue-db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - queue-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready", "-d", "postgres", "-U", "postgres"]
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  

  #-----------------------------------------------------
  # minio
  #-----------------------------------------------------
  minio:
    image: minio/minio:latest
    hostname: minio
    command: server /data --console-address ":9001" 
    expose:
      - "9000"
      - "9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: experimenteight
      MINIO_ROOT_PASSWORD: experimenteight
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5    
    volumes:
      - minio-data:/data
      

volumes:
  queue-data:
  minio-data: