services:

  #-----------------------------------------------------
  # river queue watcher
  #-----------------------------------------------------
  ui:
    image: ghcr.io/riverqueue/riverui:latest
    ports:
      - 11111:8080
    environment:
      DATABASE_URL: postgresql://postgres@queue-db:5432/postgres
      RIVER_LOG_LEVEL: ERROR
      RIVER_DEBUG: 0
    depends_on:
      queue-db:
        condition: service_healthy

  #-----------------------------------------------------
  # postgres - queue-db
  #-----------------------------------------------------
  queue-db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - queue-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready", "-d", "postgres", "-U", "postgres"]
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  

  #-----------------------------------------------------
  # minio
  #-----------------------------------------------------
  minio:
    image: minio/minio:latest
    hostname: minio
    command: server /data --console-address ":9001" 
    expose:
      - "9000"
      - "9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: nutnutnut
      MINIO_ROOT_PASSWORD: nutnutnut
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5    
    volumes:
      - minio-data:/data
      

volumes:
  queue-data:
  minio-data: