# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  install:
    docker:
      # Build against the CF image, for libc compatibiltiy reasons.
      - image: cloudfoundry/cflinuxfs4:latest
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Installing packages"
          command: "echo installing packages..."
      - run: |
            sudo apt-get update
            sudo apt-get install -y \
              build-essential \
              curl \ 
              libpoppler-dev \
              libpoppler-glib-dev \
              poppler-utils \
              software-properties-common \
              tree \
              wget
      - run: |
            rm -rf /usr/local/go
            wget https://go.dev/dl/go1.23.3.linux-amd64.tar.gz
            tar -C /usr/local -xzf go1.23.3.linux-amd64.tar.gz
      - run: |
            wget https://downloads.sqlc.dev/sqlc_1.27.0_linux_amd64.tar.gz
            tar xvzf sqlc_1.27.0_linux_amd64.tar.gz
            chmod 755 sqlc
            mv sqlc /bin/sqlc
      - run: |
            go install golang.org/x/tools/cmd/goimports@latest
            go install golang.org/x/tools/cmd/stringer@latest
            go install github.com/google/go-jsonnet/cmd/jsonnet@latest
            go install github.com/google/go-jsonnet/cmd/jsonnet-lint@latest
            go install github.com/google/go-jsonnet/cmd/jsonnetfmt@latest
      - run: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            && sh -s -- -b /usr/local/go/bin v1.62.0

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-deploy: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - install
