# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  setup:
    docker:
      # We could build against the cflinux4 image.
      # However, we'll try using the default Ubuntu image, 
      # but we could run into libc compatibility problems.
      # https://hub.docker.com/r/cloudfoundry/cflinuxfs4/tags
      # - image: cloudfoundry/cflinuxfs4:latest
      # We'll try a go image. That may, or may not,
      # build a binary that plays well with CF/CGov.
      - image: cimg/go:1.23.3
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Installing packages"
          command: "echo installing packages..."
      - run: |
            sudo apt-get update
            sudo apt-get -y install build-essential \
              curl \
              libpoppler-dev \
              libpoppler-glib-dev \
              poppler-utils \
              software-properties-common \
              tree \
              wget
      - run: |
            wget https://downloads.sqlc.dev/sqlc_1.27.0_linux_amd64.tar.gz
            tar xvzf sqlc_1.27.0_linux_amd64.tar.gz
            chmod 755 sqlc
            sudo mv sqlc /bin/sqlc
      - run: |
            # PATH=$PATH:/usr/local/go/bin:/root/go/bin
            go install golang.org/x/tools/cmd/goimports@latest
            go install golang.org/x/tools/cmd/stringer@latest
            go install github.com/google/go-jsonnet/cmd/jsonnet@latest
            go install github.com/google/go-jsonnet/cmd/jsonnet-lint@latest
            go install github.com/google/go-jsonnet/cmd/jsonnetfmt@latest
      - run: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            && sh -s -- -b /usr/local/go/bin v1.62.0
  # build:
  #   docker:
  #     - image: cimg/go:1.23.3
  #   steps:
  #     - checkout
  #     - run:
  #         name: "Building"
  #         command: "echo building..."
  #     - run: make build

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-deploy:
    jobs:
      - build