# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

commands:
  apt-packages:
    description: Performs a common install in each job
    steps:
      - run:
          name: "common apt packages"
          command: |
            sudo apt-get update
            sudo apt-get -y install build-essential \
              curl \
              libpoppler-dev \
              libpoppler-glib-dev \
              poppler-utils \
              software-properties-common \
              tree \
              wget
  install-linter:
    description: Installs the golangci linter
    parameters:
      linter-version: 
        default: 1.63.4
        type: string
    steps:
      - run:
          name: "install golangci-lint"
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v<< parameters.linter-version >>
  install-go-utilities:
    description: Installs the golang utilities
    steps:
      - run: 
          name: "install jsonnet"
          command: |
            go install golang.org/x/tools/cmd/goimports@latest
            go install golang.org/x/tools/cmd/stringer@latest
            go install github.com/google/go-jsonnet/cmd/jsonnet@latest
            go install github.com/google/go-jsonnet/cmd/jsonnet-lint@latest
            go install github.com/google/go-jsonnet/cmd/jsonnetfmt@latest
      - run: 
          name: "install sqlc"
          command: |
            wget https://downloads.sqlc.dev/sqlc_1.27.0_linux_amd64.tar.gz
            tar xvzf sqlc_1.27.0_linux_amd64.tar.gz
            chmod 755 sqlc
            sudo mv sqlc /bin/sqlc
  prep-the-build:
    description: Generates files required for the build
    steps:
      - run:
          name: "generate sqlc models"
          command: make generate
jobs:
  lint:
    docker:
      - image: cimg/go:1.23.3
    steps:
      - checkout
      - apt-packages
      - install-go-utilities
      - install-linter
      - prep-the-build
      - run: 
          name: "find the lint"
          command: golangci-lint run -v
          no_output_timeout: 5m

  setup-and-build:
    docker:
      - image: cimg/go:1.23.3
    steps:
      # Checkout the code as the first step.
      - checkout
      - apt-packages
      - install-go-utilities
      - run: make build

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-deploy:
    jobs:
      - lint
      - setup-and-build:
          requires: [ lint ]
