# https://github.com/mkdocs/catalog?tab=readme-ov-file#-navigation--page-building
site_name: Jemison Documentation
nav:
  - Home: index.md
  - Principles: principles.md
  - Tooling: tooling.md
theme: material
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
