{
   "APPENV": "LOCALHOST",
   "EIGHT_SERVICES": {
      "user-provided": [
         {
            "credentials": {
               "port": 8888
            },
            "name": "extract",
            "parameters": {
               "extract_html": true,
               "extract_pdf": true,
               "walkabout": true,
               "workers": 10
            }
         },
         {
            "credentials": {
               "port": 8888
            },
            "name": "fetch",
            "parameters": {
               "polite_cache_cleanup_interval": 300,
               "polite_cache_default_expiration": 600,
               "polite_sleep": 2,
               "workers": 10
            }
         },
         {
            "credentials": {
               "port": 8888
            },
            "name": "pack",
            "parameters": {
               "packing_timeout_seconds": 180,
               "workers": 10
            }
         },
         {
            "credentials": {
               "port": 8888
            },
            "name": "serve",
            "parameters": {
               "database_files_path": "../../assets/databases",
               "static_files_path": "../../assets/static"
            }
         },
         {
            "credentials": {
               "port": 8888
            },
            "name": "validate",
            "parameters": {
               "workers": 10
            }
         },
         {
            "credentials": {
               "port": 8888
            },
            "name": "walk",
            "parameters": {
               "cache-ttl": 1800,
               "polite_cache_cleanup_interval": 600,
               "polite_cache_default_expiration": 21600,
               "workers": 10
            }
         }
      ]
   },
   "HOME": "/home/vcap/app",
   "MEMORY_LIMIT": "512m",
   "PWD": "/home/vcap",
   "TMPDIR": "/home/vcap/tmp",
   "USER": "vcap",
   "VCAP_SERVICES": {
      "aws-rds": [
         {
            "binding_guid": "cG9zdGdyZXNxbDov",
            "binding_name": null,
            "credentials": {
               "db_name": "postgres",
               "host": "localhost",
               "name": "postgres",
               "password": "",
               "port": 5432,
               "uri": "postgresql://postgres@localhost:5432/postgres?sslmode=disable",
               "username": "postgres"
            },
            "instance_guid": "amVtaXNvbi1kYmxv",
            "instance_name": "jemison-db",
            "label": "jemison-db",
            "name": "jemison-db",
            "plan": null,
            "provider": null,
            "syslog_drain_url": "https://BRAVO.drain.url",
            "tags": [
               "aws",
               "rds",
               "postgres"
            ],
            "volume_mounts": [
               "no_mounts"
            ]
         }
      ],
      "s3": [
         {
            "binding_guid": "bWluaW8tbG9jYWxl",
            "binding_name": null,
            "credentials": {
               "access_key_id": "numbernine",
               "additional_buckets": [ ],
               "bucket": "extract",
               "endpoint": "localhost:9000",
               "fips_endpoint": "http://localhost:9000",
               "insecure_skip_verify": false,
               "port": 9000,
               "region": "us-east-1",
               "secret_access_key": "numbernine",
               "uri": "http://localhost:9000"
            },
            "instance_guid": "czMtZXh0cmFjdGV4",
            "instance_name": "extract-storage",
            "label": "s3-extract",
            "name": "extract",
            "plan": "basic",
            "provider": "minio-local",
            "syslog_drain_url": "https://ALPHA.drain.url",
            "tags": [
               "aws",
               "s3",
               "object-storage"
            ],
            "volume_mounts": [
               "no_mounts"
            ]
         },
         {
            "binding_guid": "bWluaW8tbG9jYWxm",
            "binding_name": null,
            "credentials": {
               "access_key_id": "numbernine",
               "additional_buckets": [ ],
               "bucket": "fetch",
               "endpoint": "localhost:9000",
               "fips_endpoint": "http://localhost:9000",
               "insecure_skip_verify": false,
               "port": 9000,
               "region": "us-east-1",
               "secret_access_key": "numbernine",
               "uri": "http://localhost:9000"
            },
            "instance_guid": "czMtZmV0Y2hmZXRj",
            "instance_name": "fetch-storage",
            "label": "s3-fetch",
            "name": "fetch",
            "plan": "basic",
            "provider": "minio-local",
            "syslog_drain_url": "https://ALPHA.drain.url",
            "tags": [
               "aws",
               "s3",
               "object-storage"
            ],
            "volume_mounts": [
               "no_mounts"
            ]
         },
         {
            "binding_guid": "bWluaW8tbG9jYWxz",
            "binding_name": null,
            "credentials": {
               "access_key_id": "numbernine",
               "additional_buckets": [ ],
               "bucket": "serve",
               "endpoint": "localhost:9000",
               "fips_endpoint": "http://localhost:9000",
               "insecure_skip_verify": false,
               "port": 9000,
               "region": "us-east-1",
               "secret_access_key": "numbernine",
               "uri": "http://localhost:9000"
            },
            "instance_guid": "czMtc2VydmVzZXJ2",
            "instance_name": "serve-storage",
            "label": "s3-serve",
            "name": "serve",
            "plan": "basic",
            "provider": "minio-local",
            "syslog_drain_url": "https://ALPHA.drain.url",
            "tags": [
               "aws",
               "s3",
               "object-storage"
            ],
            "volume_mounts": [
               "no_mounts"
            ]
         }
      ]
   }
}
